// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3XFiAy2JkBap7IN34jY_EFF3tPCnAD6w',
    appId: '1:788452886474:web:79c1b1a6ad8b732353b133',
    messagingSenderId: '788452886474',
    projectId: 'fir-testjustin-c0d86',
    authDomain: 'fir-testjustin-c0d86.firebaseapp.com',
    storageBucket: 'fir-testjustin-c0d86.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7vpt3qRiXHYcaG0aTGrerKca756A0o2o',
    appId: '1:788452886474:android:d07fec4cfe441cc953b133',
    messagingSenderId: '788452886474',
    projectId: 'fir-testjustin-c0d86',
    storageBucket: 'fir-testjustin-c0d86.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApYy3Z-yBFzapuf655Uf5PWUs436lCKrM',
    appId: '1:788452886474:ios:bf5e00222dd678dd53b133',
    messagingSenderId: '788452886474',
    projectId: 'fir-testjustin-c0d86',
    storageBucket: 'fir-testjustin-c0d86.appspot.com',
    iosBundleId: 'shazzanova.quaidesbananes.tiQuai',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyApYy3Z-yBFzapuf655Uf5PWUs436lCKrM',
    appId: '1:788452886474:ios:acacc4a1975612e053b133',
    messagingSenderId: '788452886474',
    projectId: 'fir-testjustin-c0d86',
    storageBucket: 'fir-testjustin-c0d86.appspot.com',
    iosBundleId: 'shazzanova.quaidesbananes.tiQuai.RunnerTests',
  );
}
